### ISSUE TITLE
Can't compile Godot with DragonBones

### ISSUE THREAD

**Issue by arisvaldez** [mauville-technologies/godot-dragonbones#27]
When i try compile Godot with DragonBones Plugin, i get the next error

modules\register_module_types.gen.cpp(72): error C3861: 'register_dragonbones_types': identifier not found
modules\register_module_types.gen.cpp(202): error C3861: 'unregister_dragonbones_types': identifier not found
scons: *** [modules\register_module_types.gen.windows.opt.tools.64.obj] Error 2

i put the repository content in a folder at module folder

Windows 10 64Bits

note: i can compile without DragonBone Plugin

**Comment by Ozzadar** [comment]
is the module located at 

`godot/modules/godot_dragonbones` ? Godot uses the folder name as the name it looks up in the `register_types` call. 

I think you've installed at `godot/modules/dragonbones`

**Comment by arisvaldez** [comment]
> 
> 
> is the module located at
> 
> `godot/modules/godot_dragonbones` ? Godot uses the folder name as the name it looks up in the `register_types` call.
> 
> I think you've installed at `godot/modules/dragonbones`

yeah, I was able to compile, thank you very much
