### ISSUE TITLE
change the method to obtain the bone position

### ISSUE THREAD

**Issue by arisvaldez** [mauville-technologies/godot-dragonbones#28]
change the method to obtain the bone position, you are currently using boneData->animationPosition,
but this returns a Vector2 (0,0), and always return the same value.

However if you get the value from boneData-> Global,
you will be able to obtain the real time value of the bone movement.

`Vector2(boneData->Global.x, boneData->Global.y)`

I already made that modification and it worked for me.

**Comment by davord45** [comment]
@arisvaldez This actually works? You get global position of the bone in Godot viewport?

**Comment by arisvaldez** [comment]
@davord45 ,That's right, I made the change that I proposed and it works wonders for me

**Comment by davord45** [comment]
Can you make a pull request? @arisvaldez 
Or maybe a build that you can share?

**Comment by arisvaldez** [comment]
I can share a compilation and also the modified code

**Comment by davord45** [comment]
I would appreciate that very much,thanks!

**Comment by arisvaldez** [comment]
u can download a build from [here](https://mega.nz/file/PF9SSIYI#fEKasZEg0Mnsp4GyyhPLxzwcf1D1y3nk-JPta0mx8_0)

godot 3.2.3

**Comment by davord45** [comment]
Thanks again!

**Comment by arisvaldez** [comment]
you can download the code from [this repo](https://github.com/arisvaldez/DragonBones.git)

I just added some methods in the **GDBone.cpp and GDBone.h**

I did not delete or replace the ones you had already put, but add more

**Comment by arisvaldez** [comment]
@davord45   look in the file
DragonBones/src/dragonBones/armature/Bone.cpp

in this file I made a modification in the method _updateGlobalTransformMatrix


I would like to make a pull request, but I have never done one, so I would not want to spoil something, jeje.

**Comment by davord45** [comment]
@arisvaldez What changes did you make in DragonBones/src/dragonBones/armature/Bone.cpp?
I don't see any changes. :/

**Comment by Ozzadar** [comment]
Weird that im not getting emails about this.

Anything left to do after the recent merge @davord45 ? Looks to me like this issue can be closed but just want to make sure.

**Comment by davord45** [comment]
Well setting the global position does not seem to be working when i try it. But i guess that is a different issue.

**Comment by Ozzadar** [comment]
Ok, I'll leave this open and look into it when I start putting together the
3.2.4 release (probably this weekend).

Thanks :)

**Comment by arisvaldez** [comment]
> @arisvaldez What changes did you make in DragonBones/src/dragonBones/armature/Bone.cpp?
> I don't see any changes. :/

I think that the change I made did not apply, and it was not relevant

**Comment by Ozzadar** [comment]
I've linked the PR that makes a few changes across the bone to the way bone position is handled to enable a `set_bone_global_position` function.
